name: "Python Container Action Template"
description: "Get list of PR branch names from list of labels"
author: "festinuz"
inputs:
  github_token:
    required: true
  labels:
    description: "Coma-separated list of labels used to filter PRs"
    required: true
outputs:
  branches:
    description: "Space-separated list of branches"
  origin_branches:
    description: "Space-separated list of branches prefixed with 'origin/'"
runs:
  using: "docker"
  image: "Dockerfile"
