name: Octopus-merge to testing
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get branch names by labels
        id: branch_names
        uses: festinuz/octupus-merge@master
        with:
          github_token: ${{ github.token }}
          labels: test

      - name: Push changes to test branch
        run: |
          echo "${{ steps.branch_names.outputs.branches }}"
          git checkout testing
          git reset --hard master --
          git merge -m "Merge branches found by labels" ${{ steps.selftest.branch_names.branches }} && git push origin HEAD --force
