name: Integration Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Self test
        id: selftest
        uses: festinuz/octupus-merge@master
        with:
          github_token: ${{ github.token }}
          labels: test

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.branches }}"
